#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("hangmanGame.Resource", IsApplication=true)]

namespace hangmanGame
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int c = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int d = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int e = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int f = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int g = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int h = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int i = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int img0 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int img00 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int img000 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int img0a = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int img1 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int img10 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int img11 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int img11a = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int img12 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int img2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int img3 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int img4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int img5 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int img6 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int img7 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int img8 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int img9 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int j = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int k = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int l = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int m = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int n = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int o = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int p = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int q = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int r = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int s = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int splash = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int t = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int u = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int v = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int w = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int x = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int xx = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int y = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int z = 2130837549;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int GUESSWORD = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int WORD = 2131099652;
			
			// aapt resource value: 0x7f060028
			public const int blockoutImg = 2131099688;
			
			// aapt resource value: 0x7f06000e
			public const int btna = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int btnb = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int btnc = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int btnd = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int btne = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int btnf = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int btng = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int btnh = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int btni = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int btnj = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int btnk = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int btnl = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int btnm = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int btnn = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int btno = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int btnp = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int btnq = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int btnr = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int btns = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int btnt = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int btnu = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int btnv = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int btnw = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int btnx = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int btny = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int btnz = 2131099687;
			
			// aapt resource value: 0x7f060008
			public const int chances = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int chancesText = 2131099657;
			
			// aapt resource value: 0x7f060029
			public const int coretextLevel = 2131099689;
			
			// aapt resource value: 0x7f06000d
			public const int hangmanimage = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int listView1 = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int relativeLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int restartgame = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int score = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int scoretext = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int scoretextLevel = 2131099660;
			
			// aapt resource value: 0x7f06002a
			public const int scoretextLevels = 2131099690;
			
			// aapt resource value: 0x7f060003
			public const int sqlite_id = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int txtNum1 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int txtNum2 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Custom_Row = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
